// Account suspension — "block login, keep content visible".
//
// THE PRODUCT RULE (owner decision, 2026-08-28). A suspended user cannot sign
// in and cannot perform authenticated actions. Suspension does NOT delete, hide
// or cancel anything they created: their reports stay visible, their completed
// missions stay in the community's history, and — the scenario the owner called
// out by name — a volunteer already helping a suspended reporter must be able to
// carry on and finish. Suspending a person must never strand a volunteer
// mid-emergency or destroy a genuine request for help.
//
// That rule is why this is a table about a PERSON'S ACCESS and nothing else.
// There is no cascade to reports, no status rewrite on missions, no filter added
// to any citizen read path. The enforcement surface is exactly two places —
// the Better Auth `session.create.before` database hook (login) and the global
// `SuspendedAccountGuard` (authenticated requests), both reading the same
// `isUserSuspended()` from the account-status module — and both gate on *the
// caller's* id. (Named by symbol rather than file: the login hook has already
// moved between files once.) A volunteer's request is never evaluated against
// the reporter's status, which is what makes Priya's mission keep working when
// Hari is suspended — by construction, not by a special case someone has to
// remember.
//
// WHY A SEPARATE TABLE RATHER THAN A COLUMN ON `user`:
//
//  1. Better Auth owns `user` (CLAUDE.md: extend, don't modify). auth-schema.ts
//     is generated by `npx auth@latest generate` and its header already lists
//     two hand-edits that must be redone after every regenerate. A third would
//     be a third chance to silently lose a security-relevant column.
//  2. Absence of a row means active — the same honest default admin_users uses
//     for "most people are not admins". No backfill, no default value that has
//     to be right, and nothing to migrate for existing accounts.
//
// Status lives in a lookup table referenced by FK, per CLAUDE.md § Database.
import { relations } from 'drizzle-orm';
import {
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';
import { user } from './auth-schema';

export const userStatuses = pgTable('user_statuses', {
  id: uuid('id').primaryKey(),
  key: text('key').notNull().unique(),
  label: text('label').notNull(),
  sortOrder: integer('sort_order').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .defaultNow()
    .notNull(),
});

/**
 * One row per user who has ever had a non-default status. No row at all is the
 * normal case and means `active`.
 *
 * Reversible by design: unsuspending sets `status_id` back to `active` and
 * clears the three suspension columns, leaving the row in place. The durable
 * history of who suspended whom, when, and why lives in `admin_audit_logs` —
 * this table only ever answers "what is true right now", which is the only
 * question the login path and the request guard need to ask.
 */
export const userAccountStatus = pgTable(
  'user_account_status',
  {
    // PK on user_id: one status per account, so "which of the two rows wins" is
    // not a question that can be asked. Same shape as admin_users.
    userId: text('user_id')
      .primaryKey()
      .references(() => user.id, { onDelete: 'cascade' }),
    statusId: uuid('status_id')
      .notNull()
      .references(() => userStatuses.id),
    // Internal moderation note. NEVER returned on any citizen-facing endpoint —
    // it is written by staff, for staff, and the suspended user is told they are
    // suspended, not what an admin wrote about them.
    reason: text('reason'),
    suspendedAt: timestamp('suspended_at', { withTimezone: true }),
    // SET NULL, not CASCADE: an admin's account being deleted must not silently
    // un-suspend everyone they actioned.
    suspendedBy: text('suspended_by').references(() => user.id, {
      onDelete: 'set null',
    }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [index('user_account_status_status_id_idx').on(table.statusId)],
);

export const userStatusRelations = relations(userStatuses, ({ many }) => ({
  accounts: many(userAccountStatus),
}));

export const userAccountStatusRelations = relations(
  userAccountStatus,
  ({ one }) => ({
    user: one(user, {
      fields: [userAccountStatus.userId],
      references: [user.id],
    }),
    status: one(userStatuses, {
      fields: [userAccountStatus.statusId],
      references: [userStatuses.id],
    }),
  }),
);
